openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Person API'
tags:
  - name: Person
    description: API endpoints to manipulate the People entity
paths:
  /person:
    get:
      summary: 'Get a list of people'
      tags:
        - Person
      parameters:
        - name: 'page'
          in: 'query'
          type: 'integer'
          default: 1
        - name: 'pageSize'
          in: 'query'
          type: 'integer'
          default: 10
      responses:
        '200':
          description: 'Successful operation'
        '500':
          description: 'Internal Server Error'
    post:
      summary: 'Create a new person'
      tags:
        - Person
      parameters:
        - name: 'body'
          in: 'body'
          schema:
            type: 'object'
            properties:
              name:
                type: 'string'
              age:
                type: 'integer'
      responses:
        '200':
          description: 'Successful operation'
        '500':
          description: 'Internal Server Error'
  /person/{id}:
    put:
      summary: 'Update a person'
      tags:
        - Person
      parameters:
        - name: 'id'
          in: 'path'
          type: 'integer'
          required: true
        - name: 'body'
          in: 'body'
          schema:
            type: 'object'
            properties:
              name:
                type: 'string'
              age:
                type: 'integer'
      responses:
        '200':
          description: 'Successful operation'
        '500':
          description: 'Internal Server Error'
    delete:
      summary: 'Delete a person'
      tags:
        - Person
      parameters:
        - name: 'id'
          in: 'path'
          type: 'integer'
          required: true
      responses:
        '200':
          description: 'Successful operation'
        '500':
          description: 'Internal Server Error'
